/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthModal: typeof import('./components/features/auth/AuthModal.vue')['default']
    Channel: typeof import('./components/layout/Channel.vue')['default']
    Comment: typeof import('./components/features/comment/Comment.vue')['default']
    CommentTree: typeof import('./components/features/comment/CommentTree.vue')['default']
    DanmakuBox: typeof import('./components/features/video-player/danmaku/DanmakuBox.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HeaderBar: typeof import('./components/layout/HeaderBar.vue')['default']
    LeftBar: typeof import('./components/features/platform/NavBar.vue')['default']
    NavBar: typeof import('./components/features/platform/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/ui/input/SearchInput.vue')['default']
    SettingPopover: typeof import('./components/features/video-player/danmaku/SettingPopover.vue')['default']
  }
}
